### ISSUE TITLE
Read from stderr

### ISSUE THREAD

**Issue by hparfr** [acsone/checklog-odoo#5]
Hi,

@sbidoul what do you think about parsing `stderr` ?

It will be simplifier than `odoo --stop-after-init 2>&1 | checklog-odoo`

**Comment by rousseldenis** [comment]
> Hi,
> 
> @sbidoul what do you think about parsing `stderr` ?
> 
> It will be simplifier than `odoo --stop-after-init 2>&1 | checklog-odoo`

@hparfr I think Odoo is writing all the logs to stderr if I remember well. That was the trigger for checklog-odoo development.

**Comment by sbidoul** [comment]
What do you mean? I don't understand.

**Comment by hparfr** [comment]
>What do you mean? I don't understand.

At the moment checklog-odoo only parse stdin.


```py
python -c "from sys import stderr, stdout; print('2024-12-18 10:47:57,389 125 ERROR db debug.checklog: not catched in stderr', file=stderr); print('2024-12-18 10:47:57,389 125 ERROR db debug.checklog: catched for stdout', file=stdout);" | checklog-odoo 
2024-12-18 10:47:57,389 125 ERROR db debug.checklog: not catched in stderr
2024-12-18 10:47:57,389 125 ERROR db debug.checklog: catched for stdout

errors that caused failure (1):
2024-12-18 10:47:57,389 125 ERROR db debug.checklog: catched for stdout

Error: Errors detected in log.

```

Docs:

>Support for - to mean a special file that refers to stdin when used for reading, and stdout when used for writing. This is a common pattern for POSIX command line utilities.

https://click.palletsprojects.com/en/stable/handling-files/#file-arguments

**Comment by sbidoul** [comment]
But stdout and stderr are write only, and there is only one stdin. So what else could we do?

**Comment by hparfr** [comment]
After some searching, I don't know how to read stderr from a previous process in the pipe.  
I don't know if it's possible

**Comment by hparfr** [comment]
Looks like I have my answer from : https://unix.stackexchange.com/questions/776898/is-it-possible-to-read-from-stderr-in-a-bash-script

`2>&1` is the way to go;

Sorry for the noise.
